-- Phantom-read
CREATE OR REPLACE PROCEDURE InsertNhanVien (
    p_TENNV IN NHANVIEN.TENNV%TYPE,
    p_CCCD IN NHANVIEN.CCCD%TYPE,
    p_GIOITINH IN NHANVIEN.GIOITINH%TYPE,
    p_NGAYSINH IN NHANVIEN.NGAYSINH%TYPE,
    p_DIACHI IN NHANVIEN.DIACHI%TYPE,
    p_LOAINV IN NHANVIEN.LOAINV%TYPE,
    p_TAIKHOAN IN NHANVIEN.TAIKHOAN%TYPE,
    p_MATKHAU IN NHANVIEN.MATKHAU%TYPE,
    p_SDT IN NHANVIEN.SDT%TYPE,
    p_LUONGCB IN NHANVIEN.LUONGCB%TYPE,
    p_TINHTRANG IN NHANVIEN.TINHTRANG%TYPE
) IS
BEGIN
    
    INSERT INTO NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB, TINHTRANG) 
    VALUES (NhanVien_Seq.NEXTVAL, p_TENNV, p_CCCD, p_GIOITINH, p_NGAYSINH, p_DIACHI, p_LOAINV, p_TAIKHOAN, p_MATKHAU, p_SDT, p_LUONGCB, p_TINHTRANG);
    
    COMMIT;
END;
/


-- Thiết lập mức độ cô lập read committed
set transaction isolation level read committed;
BEGIN
    InsertNhanVien ('Hà Thị Hiếu', '098762472131','Nữ',TO_DATE('5-7-1987', 'DD-MM-YYYY'),'123 Ðường Lý Thường Kiệt, Quảng Nam','Lễ tân','letan7','ltpass','0903276867',800000,'Ðang làm');
END;
/
COMMIT;

-- Thiết lập mức độ cô lập seriallizable
set transaction isolation level SERIALIZABLE;
BEGIN
    InsertNhanVien ( 'Phạm Thế Kiệt','098762764975','Nam', TO_DATE('5-7-1987', 'DD-MM-YYYY'),'Bình Ðình','Lễ tân','letan9','ltpass', '0903212301',800000,'Ðang làm');
END;
/


INSERT INTO DATABASE_DOAN_NPNT.NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB, TINHTRANG) 
	VALUES (NhanVien_Seq.NEXTVAL, 'Hoàng Hào Quang', '456789234512', 'Nam', TO_DATE('10-11-1992', 'DD-MM-YYYY'), '202 Đường JKL, Cần Thơ', 'Lễ tân', 'letan2', 'ltpass', '0343378901', 700000, 'Đang làm');
COMMIT;