CREATE OR REPLACE PROCEDURE GetDSKhuyenMai (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    -- Thiết lập mức độ cô lập của giao dịch
    --SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    
    OPEN p_cursor FOR
    SELECT * FROM KHUYENMAI
    ORDER BY MaKM ASC;

    -- Chờ 5 giây
    --DBMS_SESSION.SLEEP(5);
END GetDSKhuyenMai;
/


VARIABLE rc REFCURSOR;
BEGIN
    GetDSKhuyenMai(:rc);
END;
/

PRINT rc;
