CREATE OR REPLACE PROCEDURE ThemNhanVien(
    p_TENNV IN NVARCHAR2,
    p_CCCD IN CHAR,
    p_GIOITINH IN NVARCHAR2,
    p_NGAYSINH IN DATE,
    p_DIACHI IN NVARCHAR2,
    p_SDT IN CHAR,
    p_LOAINV IN NVARCHAR2,
    p_TAIKHOAN IN NVARCHAR2,
    p_MATKHAU IN NVARCHAR2,
    p_LUONGCB IN NUMBER
)
IS
BEGIN
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    -- Chèn dữ liệu vào bảng NHANVIEN
    INSERT INTO NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB, TINHTRANG) 
    VALUES (NhanVien_Seq.NEXTVAL, p_TENNV, p_CCCD, p_GIOITINH, p_NGAYSINH, p_DIACHI, p_LOAINV, p_TAIKHOAN, p_MATKHAU, p_SDT, p_LUONGCB, 'Đang làm');
END;
/

COMMIT;